# Generated by Django 3.1.2 on 2020-11-03 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20201031_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='existencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
