# Generated by Django 3.1.4 on 2020-12-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20201103_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='products'),
        ),
    ]
